[package]
edition = "2021"
name = "game-of-life"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.18.1"
# rayon = "1.6.0"
